# Generated by Django 4.2.6 on 2023-10-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_picture_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='sellername',
        ),
    ]
