# Generated by Django 4.2.6 on 2023-10-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_name_product_sellername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sellername',
            new_name='name',
        ),
    ]
