# Generated by Django 4.2.6 on 2023-10-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_name_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categorytype',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
    ]
