# Generated by Django 4.2.6 on 2023-10-18 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_category_remove_product_categorytype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='categorytype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.categorytype'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.location'),
        ),
    ]
