# Generated by Django 4.2.6 on 2023-10-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_category_product_categorytype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='name',
        ),
    ]
