# Generated by Django 4.2.6 on 2023-10-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_kilifiproduct_lamuproduct_tanariverproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kilifiproduct',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kwaleproduct',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lamuproduct',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mombasaproduct',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tanariverproduct',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mombasaproduct',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
